
services:
  mongodb:
    image: mongo:5.0
    hostname: mongodb
    networks:
      - hostnet
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: --bind_ip_all
    volumes:
      - mongodb:/data/db

  orion:
    image: quay.io/fiware/orion-ld:1.9.0
    hostname: orion
    depends_on:
      - mongodb
    networks:
      - hostnet
    ports:
      - "1026:1026"
    command: -dbhost mongodb -logLevel DEBUG
    #command: -dbhost mongodb -logLevel DEBUG -forwarding -experimental

volumes:
  mongodb: ~

networks:
  hostnet:
