openapi: 3.1.0
info:
  title: jsonld-signer
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /info:
    get:
      tags:
      - version
      operationId: service_info
      responses:
        '200':
          description: Service info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
  /sign:
    post:
      tags:
      - sign
      operationId: sign_handler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignRequest'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: {}
  /verify:
    post:
      tags:
      - verify
      operationId: verify_handler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRequest'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResult'
components:
  schemas:
    ServiceInfo:
      type: object
      required:
      - version
      - repository
      - uptime_seconds
      properties:
        repository:
          type: string
        uptime_seconds:
          type: integer
          format: int64
          minimum: 0
        version:
          type: string
    SignRequest:
      type: object
      required:
      - document
      - keysToSign
      properties:
        document: {}
        keysToSign:
          type: array
          items:
            type: string
    VerificationStatus:
      type: string
      enum:
      - 'true'
      - 'false'
      - na
    VerifyRequest:
      type: object
      required:
      - document
      properties:
        document: {}
    VerifyResult:
      type: object
      required:
      - results
      properties:
        results:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/VerificationStatus'
          propertyNames:
            type: string
tags:
- name: NGSI-LD API
  description: NGSI-LD signing and verification API
